name: check value
on: [ workflow_dispatch, on ]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      name: check value
      run: |
        echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'
