name: Create Dynamic Matrix

on:
  workflow_dispatch:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps-set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set matrix data
        id: set-matrix
        run: |
          echo "hello"
      
      
