name: Matrix from External JSON file
on:
  workflow_dispatch:

jobs:
  scan-accounts:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(env.matrix) }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Checkout matrix repo
        uses: actions/checkout@v3
        with:
          repository: your-org/your-matrix-repo
          path: matrix-repo

      - name: Load Matrix
        id: load-matrix
        run: |
          matrix=$(cat matrix-repo/path/to/matrix.json)
          echo "matrix=$matrix" >> $GITHUB_ENV

      - name: Print matrix info
        run: |
          echo "Account: ${{ matrix.account }}, Account ID: ${{ matrix.account_id }}"
