name: Matrix from External YAML file
on: [ workflow_dispatch, push ]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v4
       with:
         repository: ogie-gh/derp
         path: derp
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(yq -p yaml -o json -I=0 derp/config/matrix.yaml)" >> $GITHUB_OUTPUT
     - name: does value exist?
       run: echo $matrix

  print:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
     - run: |
         echo ${{ matrix.account }}
         echo ${{ matrix.account_id }}
