name: Matrix from External JSON file
on:
  workflow_dispatch:

jobs:
  scan-accounts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout matrix repo
        uses: actions/checkout@v4
        with:
          repository: ogie-gh/derp
          path: derp

      - name: Check dir layout
        run: ls -l

      # - name: Load Matrix
      #   id: load-matrix
      #   run: |
      #     matrix=$(cat derp/config/matrix.json)
      #     echo "matrix=$matrix" >> $GITHUB_ENV

      # - name: Run with matrix
      #   run: echo ${{ matrix.matrix }}
