name: Matrix from External JSON file
on: [ workflow_dispatch, push ]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout matrix repo
        uses: actions/checkout@v4
        with:
          repository: ogie-gh/derp
          path: derp
      - name: Set Matrix
        id: set-matrix
        run: |
          echo "matrix=$(yq -p yaml -o json -I=0 derp/config/matrix.yaml)" >> $GITHUB_ENV
          echo "MATRIX_YAML=$(yq -p yaml -o json -I=0 derp/config/matrix.yaml)" >> $GITHUB_ENV
#       run: echo "matrix=$(jq -c . < derp/config/matrix.json)" >> $GITHUB_ENV
      - name: ECHO
        run: |
          echo $matrix
          echo $MATRIX_YAML
          


  print:
    runs-on: unbuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - run: |
          echo ${{ matrix.account }}
          echo ${{ matrix.account_id }}
