name: Access my own action

on:
  workflow_dispatch:

jobs:
  create-derp:
    runs-on: ubuntu-latest
    steps:
      - name: Lets Create a Derp!
        id: derp
        uses: ogie-gh/derp/notifications@main
        with:
          prefix: TST

      - name: Get the output and use it
        run: echo ${{ steps.derp.outputs.derp-key }}
      
          
