name: Testing using Secrets as Input

on:
  workflow_dispatch:

jobs:
  create-derp:
    runs-on: ubuntu-latest
    steps:
      - name: Testing SECRETS!
        id: derp
        uses: ogie-gh/derp/notification@main
        with:
          json-input: '[{ "team":"SRE", "summary": "TEST SUMMARY", "description": "This is a test description" }]'
          auth-token: ${{ secrets.SECRET_TOKEN }}
          auth-user: ${{ secrets.SECRET_USER }}
